llm:
  base_url: "http://localhost:11434/v1"
  models:
    deepseek-r1:7b:
      temperature: 0.7
      max_tokens: 4096
      frequency_penalty: 0.1
      presence_penalty: 0.1
      top_p: 0.9
      stop: ["<｜end▁of▁sentence｜>"]